[package]
edition = "2021"
name = "flashback"
description = "An image viewer"
version = "0.1.0"

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }
bevy = { version = "0.7.0", features = ["jpeg"] }
glob = "0.3.0"
bevy_prototype_lyon = "0.5.0"

[profile.release]
debug = true
